# Spotify 规则 for Loon
USER-AGENT,Spotify*,Proxy
DOMAIN-KEYWORD,spotify,Proxy
DOMAIN-SUFFIX,pscdn.co,Proxy
DOMAIN-SUFFIX,scdn.co,Proxy
DOMAIN-SUFFIX,spoti.fi,Proxy
DOMAIN-SUFFIX,spotify.com,Proxy
DOMAIN-SUFFIX,spotifycdn.com,Proxy
DOMAIN-SUFFIX,spotifycdn.net,Proxy
